language: node_js
before_script:
- yarn install
- yarn run build
node_js:
- node
deploy:
  app: py-crumbs
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: hE38imLtqx8lMdJyB1st8JkLCbIhIIJDeJpkKc3ak0NZiDXluNXcb3nRqLGzM3Llw2jFZI/xK9dnPaf10dX+ajLhcucbYheKz2CthJXArNeKRFmGzFTWvyd1/hn0IXCQ0f7DhXODVTQqEqMGMM69xjiYl7DaAY6YACnc25rn1o35vyO0J6jC4G7ARRhAf+K4r0Midfb4NeDcFrw9mgc831cGzTIH2Na1nKJr0nXVRgIAEoxSwFE9tkH2rfnqV5JBSOntHIQdpXPaFpox51XlZbR9kGjpprI2zxzqTbu+bNyY0TRTF7DaIVLr6Cj7/zXOyG7X/w5bDp/2FDkQREPU6cBmmwvT9qR+58mvQLjwc+T2S1eyuH84RaqgcUJQKWjs+exUrkKiiBewOaAvnUlmHBuS00G/f4ze477CU8ygeo6zjQkb2geonJHaeR52ypOi946VbTAkjRlrZhcondMLCKSENuj4MCqxxXHOqBWfvCbNtFf+nc/FM1LXBKIkvFIrpizlRpp0xF2541ZgHtYSdWqcMydMzNJnzhVfwTCQVOcLhpVTu5legJ2UVFAdluKA4rlROfvSsx0Cs35quS1tvdl1v2OIqfzzwZ2AMrZonlyMReWiign+SjCfZJYUlONpA006eEV8aLX6Gzz13WLugHdb5b9UXjbre4vLvExHd0k=
